export { default } from "./src/wallet-manager-multisig-solana-squads.js";
export { default as WalletAccountMultisigSolanaSquads, PERMISSION } from "./src/wallet-account-multisig-solana-squads.js";
export type MultisigInfo = import("@tetherto/wdk-wallet/multisig").MultisigInfo;
export type MultisigProposal = import("@tetherto/wdk-wallet/multisig").MultisigProposal;
export type MultisigInteractionResult = import("@tetherto/wdk-wallet/multisig").MultisigInteractionResult;
export type MultisigTransactionOptions = import("@tetherto/wdk-wallet/multisig").MultisigTransactionOptions;
export type MultisigOptions = import("@tetherto/wdk-wallet/multisig").MultisigOptions;
export type TransactionResult = import("@tetherto/wdk-wallet").TransactionResult;
export type SimpleSolanaTransaction = import("@tetherto/wdk-wallet-solana").SimpleSolanaTransaction;
export type SolanaTransactionReceipt = import("@tetherto/wdk-wallet-solana").SolanaTransactionReceipt;
export type SolanaMultisigSquadsSigningConfig = import("./src/wallet-account-read-only-multisig-solana-squads.js").SolanaMultisigSquadsSigningConfig;
export type SolanaMultisigSquadsConfig = import("./src/wallet-account-read-only-multisig-solana-squads.js").SolanaMultisigSquadsConfig;
export type SolanaMultisigSquadsReadOnlyConfig = import("./src/wallet-account-read-only-multisig-solana-squads.js").SolanaMultisigSquadsReadOnlyConfig;
export type SolanaMultisigInfo = import("./src/wallet-account-read-only-multisig-solana-squads.js").SolanaMultisigInfo;
export type SolanaMultisigProposal = import("./src/wallet-account-read-only-multisig-solana-squads.js").SolanaMultisigProposal;
export type SolanaMultisigProposalResult = import("./src/wallet-account-multisig-solana-squads.js").SolanaMultisigProposalResult;
export type SolanaMultisigTransactionOptions = import("./src/wallet-account-multisig-solana-squads.js").SolanaMultisigTransactionOptions;
export type SolanaMultisigAddOwnerOptions = import("./src/wallet-account-multisig-solana-squads.js").SolanaMultisigAddOwnerOptions;
export type MultisigCoordinatorFactory = import("./src/coordinators/index.js").MultisigCoordinatorFactory;
export type SquadsMember = import("./src/wallet-account-read-only-multisig-solana-squads.js").SquadsMember;
export type SquadsMultisigAccount = import("./src/wallet-account-read-only-multisig-solana-squads.js").SquadsMultisigAccount;
export type SquadsProposalAccount = import("./src/wallet-account-read-only-multisig-solana-squads.js").SquadsProposalAccount;
export type SquadsAddressTableLookup = import("./src/wallet-account-read-only-multisig-solana-squads.js").SquadsAddressTableLookup;
export type SquadsTransactionMessage = import("./src/wallet-account-read-only-multisig-solana-squads.js").SquadsTransactionMessage;
export type SquadsTransactionKind = import("./src/wallet-account-read-only-multisig-solana-squads.js").SquadsTransactionKind;
export type SquadsConfigActionKind = import("./src/wallet-account-read-only-multisig-solana-squads.js").SquadsConfigActionKind;
export type SquadsConfigAction = import("./src/wallet-account-read-only-multisig-solana-squads.js").SquadsConfigAction;
export type SquadsTransactionAccount = import("./src/wallet-account-read-only-multisig-solana-squads.js").SquadsTransactionAccount;
export type SquadsProgramConfig = import("./src/wallet-account-read-only-multisig-solana-squads.js").SquadsProgramConfig;
export type SquadsProposalContext = import("./src/wallet-account-read-only-multisig-solana-squads.js").SquadsProposalContext;
export { default as WalletAccountReadOnlyMultisigSolanaSquads, PROPOSAL_DATA_MASK, SQUADS_PROGRAM_ADDRESS, TRANSACTION_KIND } from "./src/wallet-account-read-only-multisig-solana-squads.js";
export { IMultisigCoordinator } from "./src/coordinators/index.js";
export { AccountNotOwnerError, ThresholdNotMetError } from "@tetherto/wdk-wallet/multisig";
export { AssertionError, InvalidTokenError, MaximumFeeExceededError, NoSuchElementError, NotImplementedError, ProviderError, ProviderErrorReason, ProviderRequiredError, UnsupportedOperationError, ValueError, WdkError } from "@tetherto/wdk-wallet";
